### ISSUE TITLE
cannot run the classifier into trump_tweets.csv

### ISSUE THREAD

**Issue by terry07** [t-davidson/hate-speech-and-offensive-language#3]
After having installed all the prerequisite packages, the next message appears after the command python2 classifier.py :
Loading data to classify...
29885  tweets to classify
Loading trained classifier... 
/home/user/anaconda2/lib/python2.7/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator LinearSVC from version 0.18 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Loading other information...
/home/user/anaconda2/lib/python2.7/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator TfidfTransformer from version 0.18 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/user/anaconda2/lib/python2.7/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator TfidfVectorizer from version 0.18 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Transforming inputs...
Built TF-IDF array
Built POS array
Traceback (most recent call last):
  File "classifier.py", line 227, in <module>
    X = transform_inputs(tweets, tf_vectorizer, idf_vector, pos_vectorizer)
  File "classifier.py", line 176, in transform_inputs
    oth_array = get_oth_features(tweets)
  File "classifier.py", line 149, in get_oth_features
    feats.append(other_features_(t))
  File "classifier.py", line 124, in other_features_
    syllables = textstat.syllable_count(words) #count syllables in words
  File "/home/user/anaconda2/lib/python2.7/site-packages/repoze/lru/__init__.py", line 348, in cached_wrapper
    val = func(*args, **kwargs)
  File "/home/user/anaconda2/lib/python2.7/site-packages/textstat/textstat.py", line 63, in syllable_count
    word_hyphenated = dic.inserted(word)
  File "/home/user/anaconda2/lib/python2.7/site-packages/pyphen/__init__.py", line 298, in inserted
    for position in reversed(self.positions(word)):
  File "/home/user/anaconda2/lib/python2.7/site-packages/pyphen/__init__.py", line 248, in positions
    return [i for i in self.hd.positions(word) if self.left <= i <= right]
  File "/home/user/anaconda2/lib/python2.7/site-packages/pyphen/__init__.py", line 197, in positions
    pointed_word = '.%s.' % word
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 18: ordinal not in range(128)

**Comment by t-davidson** [comment]
Please pull the latest version and check if it works now as @yonilx should have fixed it. I was unable to replicate the issue on my machine.

**Comment by t-davidson** [comment]
The issue should be resolved. Closing due to inactivity.
